---
title: "Network analysis of alcohol data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('~/GitHub/Networks/Network_Analysis_Tools.R')
library(data.table)
library(pheatmap)
library(RColorBrewer)

```


```{r read data and add graph info}
dane<-fread("C:/Users/Monik/Documents/GitHub/sredni_sygnal_mozgu/pliki/summarized_unweighted_alcohol.csv")

dane[,idx:=NULL]
dane[,group_id:=NULL]

parents<-fread("C:/Users/Monik/Documents/GitHub/sredni_sygnal_mozgu/pliki/parents.txt", header = FALSE)
setnames(parents, c("V1", "V2"), c("abbrev", "parent"))
dane<-merge(dane, parents, by = "abbrev", sort = FALSE)
dane[, is_parent:= abbrev %in% unique(dane$parent) ]
```

```{r kategorie Marzeny}
kategorie<-c("Cortical subplate", "Cortical plate", "Striatum", "Pallidum", "Thalamus", "Hypothalamus", "Midbrain", "Hindbrain")
kat<-unique(dane[name %in% kategorie]$abbrev) #skroty nazw powyzej

for(k0 in kat) { #po kolei dla kazdej kategorii
  k=k0
  indx=dane[abbrev==k, which=TRUE]
  d<-dane[indx]$depth[1]
  
  while(d<10) {
    new_indx=dane[parent %in% k, which=TRUE]
    indx=c(indx, new_indx)
    k<-unique(c(k, dane[indx]$abbrev))
    d<-d+1
  }
  
 dane[indx, category:=k0]
  
}

dane[,category:=as.factor(category
                          )] #kolejnosc jak w PNAS

lookup<-unique(dane[,c("abbrev", "category")])

categories_for_labeling <- data.frame(category=lookup$category)
row.names(categories_for_labeling)<-lookup$abbrev
```



```{r make list of groups and calculate correlation matrices}

level_wanted=5 #highest depth of structures considered
dane_wybrane<-dane[category!="" &(depth==level_wanted | (depth<level_wanted & !is_parent))]
dane_wybrane[,c("name", "depth", "parent", "is_parent"):=NULL]

#split by group
lista.danych<-split(dane_wybrane, by="group_label", keep.by=FALSE)
lista.danych<-lapply(lista.danych, 
                     function(x) {
                       transpose(dcast(x, abbrev ~ case_id, value.var = "cell_count"), make.names = "abbrev")})
lista.danych<-lapply(lista.danych, function(x) setDF(x))
lista.danych <- lapply(lista.danych, clean_data, missing_thresh=3, fill_missing=FALSE, real_zeros=FALSE)
common.regions <- intersect(intersect(colnames(lista.danych[[1]]), colnames(lista.danych[[2]])),
                            intersect(colnames(lista.danych[[3]]), colnames(lista.danych[[4]])))
lista.danych <- lapply(lista.danych, function(x) x[, colnames(x) %in% common.regions])

#correlations
lista.corr <- lapply(lista.danych, function(x) rcorr(as.matrix(x))$r)
lista.corr <- lapply(lista.corr, function(x) {diag(x) <- 0; x})

```
## Including Plots


```{r plot heatmap, fig.width=12,fig.height=10}

# choose data 
mymatrix <- lista.corr[["control"]]

# reorder matrix according to atlas
kolejnosc<-colnames(mymatrix)
kolejnosc<-kolejnosc[order(match(kolejnosc, lookup$abbrev))]
mymatrix<-mymatrix[kolejnosc, kolejnosc]

# creat heatmap with row annotations
my_heatmap<-pheatmap(mymat, cluster_cols = F, cluster_rows = F, annotation_row = categories_for_labeling)

print(my_heatmap)
```


```{r}


save_pheatmap_png <- function(x, filename, width=1200, height=1000, res = 150) {
  png(filename, width = width, height = height, res = res)
  grid::grid.newpage()
  grid::grid.draw(x$gtable)
  dev.off()
}
 
save_pheatmap_png(my_heatmap, "my_heatmap.png")

```

```{r old heatmap}
col<- colorRampPalette(c("blue", "white", "red"))(20)

heatmap(x = lista.corr[['alcohol']], col = col, symm = TRUE)

```
```{r code from Kamil for making graphs - not changed yet}
#Get threshold to make networks the same density
cost = 0.8
l.threshold <- lapply(lista.corr, function(x) quantile(abs(x), probs=cost, na.rm=TRUE))
l.G <- mapply(df_to_igraph, lista.danych, l.threshold, negs=TRUE, thresh.param='r', SIMPLIFY=FALSE)


#Get some centrality measures for each graph
l.df.centrality <- lapply(l.G, get_centrality_measures)
l.df.centrality <- lapply(l.df.centrality, function(x) {x$region <- rownames(x) ; x})


#Make a couple of figures; let's sort by degree first
l.df.centrality <- lapply(l.df.centrality, function(x) {out <- x[order(x$degree, decreasing=TRUE),] ; out})
#need to reorder the factors
l.df.centrality <- lapply(l.df.centrality, function(x) {x$region <- factor(x$region, levels=x$region) ; x})

#now let's plot
lapply(seq_along(l.df.centrality), function(d,y,i) {ggplot(d[[i]], aes(x=region, y=degree)) + 
                                                      geom_bar(stat='identity') + 
                                                      ggtitle(y[[i]])}, d = l.df.centrality, y=names(l.df.centrality))
```

```{r}

#Now for betweenness
l.df.centrality <- lapply(l.df.centrality, function(x) {out <- x[order(x$betweenness, decreasing=TRUE),] ; out})
#need to reorder the factors
l.df.centrality <- lapply(l.df.centrality, function(x) {x$region <- factor(x$region, levels=x$region) ; x})

#now let's plot
lapply(seq_along(l.df.centrality), function(d,y,i) {ggplot(d[[i]], aes(x=region, y=betweenness)) + 
                                                      geom_bar(stat='identity') + 
                                                      ggtitle(y[[i]])}, d = l.df.centrality, y=names(l.df.centrality))
```